apiVersion: v1
kind: Service
metadata:
  name: compiler
  namespace: dyocense
spec:
  selector:
    app: compiler
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compiler
  namespace: dyocense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compiler
  template:
    metadata:
      labels:
        app: compiler
    spec:
      containers:
        - name: compiler
          image: ghcr.io/dyocense/compiler:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dyocense-config
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
