apiVersion: v1
kind: Service
metadata:
  name: diagnostician
  namespace: dyocense
spec:
  selector:
    app: diagnostician
  ports:
    - port: 8006
      targetPort: 8006
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnostician
  namespace: dyocense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diagnostician
  template:
    metadata:
      labels:
        app: diagnostician
    spec:
      containers:
        - name: diagnostician
          image: ghcr.io/dyocense/diagnostician:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dyocense-config
          ports:
            - containerPort: 8006
