apiVersion: v1
kind: Service
metadata:
  name: evidence
  namespace: dyocense
spec:
  selector:
    app: evidence
  ports:
    - port: 8007
      targetPort: 8007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidence
  namespace: dyocense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evidence
  template:
    metadata:
      labels:
        app: evidence
    spec:
      containers:
        - name: evidence
          image: ghcr.io/dyocense/evidence:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dyocense-config
          ports:
            - containerPort: 8007
