apiVersion: v1
kind: Service
metadata:
  name: explainer
  namespace: dyocense
spec:
  selector:
    app: explainer
  ports:
    - port: 8004
      targetPort: 8004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explainer
  namespace: dyocense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explainer
  template:
    metadata:
      labels:
        app: explainer
    spec:
      containers:
        - name: explainer
          image: ghcr.io/dyocense/explainer:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dyocense-config
          ports:
            - containerPort: 8004
