apiVersion: v1
kind: Service
metadata:
  name: forecast
  namespace: dyocense
spec:
  selector:
    app: forecast
  ports:
    - port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast
  namespace: dyocense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecast
  template:
    metadata:
      labels:
        app: forecast
    spec:
      containers:
        - name: forecast
          image: ghcr.io/dyocense/forecast:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dyocense-config
          ports:
            - containerPort: 8003
