apiVersion: v1
kind: Service
metadata:
  name: marketplace
  namespace: dyocense
spec:
  selector:
    app: marketplace
  ports:
    - port: 8008
      targetPort: 8008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace
  namespace: dyocense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace
  template:
    metadata:
      labels:
        app: marketplace
    spec:
      containers:
        - name: marketplace
          image: ghcr.io/dyocense/marketplace:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dyocense-config
          ports:
            - containerPort: 8008
