apiVersion: v1
kind: Service
metadata:
  name: optimiser
  namespace: dyocense
spec:
  selector:
    app: optimiser
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimiser
  namespace: dyocense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimiser
  template:
    metadata:
      labels:
        app: optimiser
    spec:
      containers:
        - name: optimiser
          image: ghcr.io/dyocense/optimiser:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dyocense-config
          ports:
            - containerPort: 8002
