apiVersion: v1
kind: Service
metadata:
  name: policy
  namespace: dyocense
spec:
  selector:
    app: policy
  ports:
    - port: 8005
      targetPort: 8005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy
  namespace: dyocense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy
  template:
    metadata:
      labels:
        app: policy
    spec:
      containers:
        - name: policy
          image: ghcr.io/dyocense/policy:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dyocense-config
          ports:
            - containerPort: 8005
